In [20]:
import pennylane as qml
import numpy as np

#U = np.array([[1, 0,0,0], [0,1,0,0], [0,0,1,0],[0,0,0, 1j]])
#gate =  qml.QubitUnitary(U, wires=[0,1])

gate = qml.CZ

U_matrix = np.array(gate.compute_matrix())
print(U_matrix)
U_adjoint = np.array(qml.adjoint(gate).compute_matrix())
print(U_adjoint)

Z = np.array(qml.PauliZ.compute_matrix())
X = np.array(qml.PauliX.compute_matrix())
I = np.identity(2)
basis = [np.kron(X, I), np.kron(Z, I), np.kron(I, X), np.kron(I, Z)]
correction_operator = []

for base in basis:
    result = np.matmul(U_matrix, base)
    result = np.matmul(result, U_adjoint)
    result = qml.pauli.pauli_decompose(result)
    
    # Access the Pauli decomposition
    # print(result)
    
    for r in result.ops:
        r1, r2 = r.obs[0].name, r.obs[1].name
        correction_operator.append((r1, r2))

print(correction_operator)
    



[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0 -1]]
[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0 -1]]
[('PauliX', 'PauliZ'), ('PauliZ', 'Identity'), ('PauliZ', 'PauliX'), ('Identity', 'PauliZ')]
